ALTER TABLE modeling.data_model
  ADD COLUMN IF NOT EXISTS pipeline_mode VARCHAR(32) NOT NULL DEFAULT 'SYSTEM_GENERATED',
  ADD COLUMN IF NOT EXISTS operator_graph_version INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS operator_graph JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS resource_group VARCHAR(64) NOT NULL DEFAULT 'default',
  ADD COLUMN IF NOT EXISTS compute_profile VARCHAR(64) NOT NULL DEFAULT 'trino-small',
  ADD COLUMN IF NOT EXISTS engine VARCHAR(32) NOT NULL DEFAULT 'TRINO_DBT',
  ADD COLUMN IF NOT EXISTS cost_policy JSONB NOT NULL DEFAULT '{}'::jsonb;
