ALTER TABLE catalog.asset
  ADD COLUMN IF NOT EXISTS domain VARCHAR(128),
  ADD COLUMN IF NOT EXISTS owner_name VARCHAR(128),
  ADD COLUMN IF NOT EXISTS popularity INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS access_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS row_count BIGINT,
  ADD COLUMN IF NOT EXISTS size_bytes BIGINT,
  ADD COLUMN IF NOT EXISTS partitions JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS format VARCHAR(32),
  ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMPTZ;

UPDATE catalog.asset
SET partitions = '[]'::jsonb
WHERE partitions IS NULL;
