FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-postgres

WORKDIR /opt/dagster/app
COPY definitions.py /opt/dagster/app/definitions.py

EXPOSE 4000
HEALTHCHECK --timeout=2s --start-period=5s --interval=5s --retries=20 CMD ["dagster", "api", "grpc-health-check", "-p", "4000"]
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]
